---
title: "Initial Data Analysis"
ipsum_meta:
  twitter_card: "Summary info for the Twitter Card"
  twitter_site: "\\@sitehandle"
  twitter_creator: "\\@creatorhandle"
  og_url: "https\\://example.com/open/graph/finalURLfor/this"
  og_description: "A modest size description of the content"
  og_image: "https\\://example.com/open/graph/imageURLfor/this"
output: 
  hrbrthemes::ipsum:
    toc: true
---
```{r include=FALSE}
knitr::opts_chunk$set(fig.retina=2)
```

```{r setup, message=FALSE, warning=FALSE, cache=FALSE, echo=FALSE}
library(hrbrthemes)
library(tidyverse)
library(faraway)

update_geom_font_defaults(font_rc)
```


# Chapter 1


## Load PIMA data

```{r}
data(pima)
head(pima)


```

### Initial Analysis

```{r}
summary(pima)
sort(pima$diastolic)

```

```{r}

pima$diastolic[pima$diastolic == 0] <- NA  
pima$glucose[pima$glucose == 0] <- NA  
pima$triceps[pima$triceps == 0] <- NA  
pima$insulin[pima$insulin == 0] <- NA  
pima$bmi[pima$bmi == 0] <- NA  


pima$test <- factor(pima$test)
levels(pima$test) <- c("negative","positive") 

summary(pima)  


```



### Plot Data

```{r}

hist(pima$diastolic, xlab='Diastolic', main='')

plot(density(pima$diastolic,na.rm=TRUE),main="")  

plot(sort(pima$diastolic),ylab="Sorted Diastolic")  


```





```{r}

plot(diabetes ~ diastolic,pima) 
plot(diabetes ~ test,pima) 



```



### GGPlot


```{r}

require(ggplot2) 
ggplot(pima,aes(x=diastolic))+geom_histogram()  
ggplot(pima,aes(x=diastolic))+geom_density()  
ggplot(pima,aes(x=diastolic,y=diabetes))+geom_point()  


```

```{r}

ggplot(pima,aes(x=diastolic,y=diabetes,shape=test)) +
	geom_point() +  
	theme(legend.position = "top", legend.direction = "horizontal")  

ggplot(pima,aes(x=diastolic,y=diabetes)) + 
	geom_point(size=1) +  
	facet_grid(~ test)  

```




## Linear Modeling




```{r}
data(manilius)
head(manilius)
summary(manilius)


```




```{r}

(moon3 <- aggregate(manilius[,1:3],list(manilius$group), sum)) 






```


```{r}

solve(cbind(9,moon3$sinang,moon3$cosang), moon3$arc) 


```


```{r}

lmod <- lm(arc ~ sinang + cosang, manilius)
coef(lmod)  


```




### HistData


```{r}
library(HistData)
data(GaltonFamilies, package="HistData")
 



```




```{r}
plot(childHeight ~ midparentHeight, GaltonFamilies) 
lmod <- lm(childHeight ~ midparentHeight, GaltonFamilies) 

coef(lmod)  
abline(lmod)


```




```{r}

(beta <- with(GaltonFamilies, cor(midparentHeight, childHeight) * sd  (childHeight)/ sd(midparentHeight))) 
(alpha <- with(GaltonFamilies, mean(childHeight) - beta * mean(  midparentHeight))) 

```




```{r}
plot(childHeight ~ midparentHeight, GaltonFamilies) 
(beta1 <- with(GaltonFamilies, sd(childHeight)/ sd(midparentHeight)  ))  
(alpha1 <- with(GaltonFamilies, mean(childHeight) - beta1 * mean(  midparentHeight)))  



abline(alpha1, beta1, lty=2)  


```












