---
title: "w2_linear_regression"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
```


```{r}

library(MASS)
library(ISLR)


```




## Simple Linear Regression

```{r}

names(Boston)
?Boston
data(Boston)


```



```{r}

plot(medv ~ lstat, data=Boston)


```





```{r}

plot(medv ~ lstat, data=Boston)
fit1 <- lm(medv ~ lstat, data=Boston)
abline(fit1, col='blue')
summary(fit1)
confint(fit1)


```




```{r}

predict(fit1, data.frame(lstat=c(5,10.15)), interval='confidence')


```



## multiple linear regression

```{r}

plot(medv ~ lstat + age, data=Boston)
fit2 <- lm(medv ~ lstat + age, data=Boston)
abline(fit2, col='blue')
summary(fit2)
confint(fit2)



```




```{r}

fit3 <- lm(medv ~ . , data=Boston)
summary(fit3)
par(mfrow=c(2,2))
plot(fit3)


```




```{r}

fit4 <- update(fit3, ~. -age -indus) 
summary(fit4)
par(mfrow=c(2,2))
plot(fit4)


```



## non linear term interaction


```{r}

fit5 <- lm(medv ~ lstat*age, Boston)
summary(fit5)
par(mfrow=c(2,2))
plot(fit5)



```



```{r}

fit6 <- lm(medv ~ lstat +I(lstat^2), Boston)
summary(fit6)
par(mfrow=c(2,2))
plot(fit6)


attach(Boston)
par(mfrow=c(1,1))
plot(medv~lstat)
points(lstat,fitted(fit6), col='red', pch=20)


fit7 <- lm(medv~poly(lstat,4))
points(lstat,fitted(fit7), col='blue', pch=20)

```



# Qualitative Predictors


```{r}


fix(Carseats)
names(Carseats)
attach(Carseats)

```




```{r}

fit1 <- lm(Sales ~ .+Income:Advertising+Age:Price, Carseats)
summary(fit1)
contrasts(Carseats$ShelveLoc)


```

